---
# install_openssh-server_on_OpenWRT/tasks/main.yml

#
# update opkg cache
#

- name: 'Run opkg update'
  raw: '/bin/opkg update'
  args:
    executable: '/bin/ash'
  changed_when: 'false'
  when: 'ansible_distribution == "OpenWrt"'

#
# install the openssh-server packages
#
- name: 'Install the openssh server packages'
  opkg:
    name: "{{ item }}"
    state: 'installed'
    update_cache: 'true'
  with_items:
    - 'openssh-server'
    - 'openssh-keygen'
    - 'openssh-sftp-server'
  notify:
    - 'disable the dropbear service'
    - 'enable the sshd service'
    - 'delete public and private host key files'
  when: 'ansible_distribution == "OpenWrt"'

#
# Configure host keys for sshd
#
- name: 'Copy the existing dropbear host keys to avoid warnings'
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: 'true'
    owner: 'root'
    group: 'root'
    mode: '0600'
  with_items:
    - { src: '/etc/dropbear/dropbear_rsa_host_key', dest: '/etc/ssh/ssh_host_rsa_key'}
    - { src: '/etc/dropbear/dropbear_ed25519_host_key', dest: '/etc/ssh/ssh_host_ed25519_key'}
  ignore_errors: "{{ ansible_check_mode }}"
