---
# install_openssh-server_on_OpenWRT/tasks/main.yml

#
# safe guard when connection as root user
#
- name: 'Check if /etc/dropbear/authorized_keys exists'
  ansible.builtin.stat:
    path: '/etc/dropbear/authorized_keys'
  register: does_etc_dropbear_authorized_keys_exist

- name: 'Abort if running as root user and there is no authorized_keys file'
  ansible.builtin.fail:
  when:
    - 'ansible_user == "root"'
    - 'does_etc_dropbear_authorized_keys_exist.stat.exists == false'

#
# update opkg cache
#

- name: 'Run opkg update'
  ansible.builtin.raw: '/bin/opkg update'
  args:
    executable: '/bin/ash'
  changed_when: 'false'
  when: 'ansible_distribution == "OpenWrt"'

#
# install the openssh-server packages
#
- name: 'Install the openssh server packages'
  ansible.builtin.package:
    name: "{{ item }}"
    state: 'installed'
    update_cache: 'true'
  with_items:
    - 'openssh-server-pam'
    - 'openssh-keygen'
    - 'openssh-sftp-server'
  notify:
    - 'Disable the dropbear service'
    - 'Delete public and private host key files'
    - 'Install dropbearconvert'
    - 'Convert dropbear keys to OpenSSH'
    - 'Create pub files'
    - 'Uninstall dropbearconvert'
  when: 'ansible_distribution == "OpenWrt"'

- name: 'Create the /root/.ssh/ directory'
  ansible.builtin.file:
    path: '/root/.ssh/'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0700'
  when:
    - 'ansible_user == "root"'

- name: 'Copy the dropbear authorized_keys to /root/.ssh/'
  ansible.builtin.copy:
    src: '/etc/dropbear/authorized_keys'
    dest: '/root/.ssh/authorized_keys'
    remote_src: 'true'
    owner: 'root'
    group: 'root'
    mode: '0600'
    force: 'no'
  when:
    - 'ansible_user == "root"'

- name: 'Flush handlers'
  ansible.builtin.meta: flush_handlers

- name: 'Enable the sshd service'
  ansible.builtin.service:
    name: 'sshd'
    enabled: 'true'
  when:
    - 'ansible_distribution == "OpenWrt"'

- name: 'Start the sshd service'
  ansible.builtin.service:
    name: 'sshd'
    state: 'started'
  when:
    - 'ansible_distribution == "OpenWrt"'
