---
# install_openssh-server_on_OpenWRT/tasks/main.yml

#
# safe guard when connection as root user
#
- name: 'Check if /etc/dropbear/authorized_keys exists'
  stat:
    path: '/etc/dropbear/authorized_keys'
  register: does_etc_dropbear_authorized_keys_exist

- name: 'Abort if running as root user and there is no authorized_keys file'
  fail:
  when:
    - 'ansible_user == "root"'
    - 'does_etc_dropbear_authorized_keys_exist.stat.exists == false'

#
# update opkg cache
#

- name: 'Run opkg update'
  raw: '/bin/opkg update'
  args:
    executable: '/bin/ash'
  changed_when: 'false'
  when: 'ansible_distribution == "OpenWrt"'

#
# install the openssh-server packages
#
- name: 'Install the openssh server packages'
  opkg:
    name: "{{ item }}"
    state: 'installed'
    update_cache: 'true'
  with_items:
    - 'openssh-server'
    - 'openssh-keygen'
    - 'openssh-sftp-server'
  notify:
    - 'disable the dropbear service'
    - 'enable the sshd service'
    - 'delete public and private host key files'
    - 'install dropbearconvert'
    - 'convert dropbear keys to OpenSSH'
    - 'create pub files'
    - 'uninstall dropbearconvert'
  when: 'ansible_distribution == "OpenWrt"'

- name: 'Create the /root/.ssh/ directory'
  file:
    path: '/root/.ssh/'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0700'
  when:
    - 'ansible_user == "root"'

- name: 'Copy the dropbear authorized_keys to /root/.ssh/'
  copy:
    src: '/etc/dropbear/authorized_keys'
    dest: '/root/.ssh/authorized_keys'
    remote_src: 'true'
    owner: 'root'
    group: 'root'
    mode: '0600'
  when:
    - 'ansible_user == "root"'
