---
# install_openssh-server_on_OpenWRT/handlers/main.yml

- name: 'disable the dropbear service'
  service:
    name: 'dropbear'
    enabled: 'false'
  when: 'ansible_distribution == "OpenWrt"'

- name: 'enable the sshd service'
  service:
    name: 'sshd'
    enabled: 'true'
  when: 'ansible_distribution == "OpenWrt"'

- name: 'delete public host key files'
  file:
    name: "/etc/ssh/{{ item }}"
    state: 'absent'
  with_items:
    - 'ssh_host_ed25519_key.pub'
    - 'ssh_host_rsa_key.pub'
  when: 'ansible_distribution == "OpenWrt"'
