---
# install_openssh-server_on_OpenWRT/handlers/main.yml

- name: 'disable the dropbear service'
  service:
    name: 'dropbear'
    enabled: 'false'
  when: 'ansible_distribution == "OpenWrt"'

- name: 'delete public and private host key files'
  file:
    name: "/etc/ssh/{{ item }}"
    state: 'absent'
  with_items:
    - 'ssh_host_ed25519_key'
    - 'ssh_host_ed25519_key.pub'
    - 'ssh_host_rsa_key'
    - 'ssh_host_rsa_key.pub'
  when: 'ansible_distribution == "OpenWrt"'

- name: 'install dropbearconvert'
  opkg:
    name: 'dropbearconvert'
    state: 'present'

- name: 'convert dropbear keys to OpenSSH'
  command:
    cmd: "dropbearconvert dropbear openssh /etc/dropbear/{{ item.dropbearname }} /etc/ssh/{{ item.openssh_name }}"
  with_items:
    - dropbearname: 'dropbear_rsa_host_key'
      openssh_name: 'ssh_host_rsa_key'
    - dropbearname: 'dropbear_ed25519_host_key'
      openssh_name: 'ssh_host_ed25519_key'

- name: 'create pub files'
  shell:
    cmd: 'dropbearkey -y -f /etc/dropbear/{{ item.dropbearname }} |grep {{ item.string_for_grep }} > /etc/ssh/{{ item.openssh_pub_name }}'
    creates: "/etc/ssh/{{ item.openssh_pub_name }}"
  with_items:
    - dropbearname: 'dropbear_rsa_host_key'
      openssh_pub_name: 'ssh_host_rsa_key.pub'
      string_for_grep: 'rsa'
    - dropbearname: 'dropbear_ed25519_host_key'
      openssh_pub_name: 'ssh_host_ed25519_key.pub'
      string_for_grep: 'ed25519'

- name: 'uninstall dropbearconvert'
  opkg:
    name: 'dropbearconvert'
    state: 'absent'
